# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ work ]

jobs:
  build:
    runs-on: self-hosted

    env:
      DEPLOY_PATH: "C:/gritlabs"          # adjust once you decide the IIS path

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Create virtual environment & Install dependencies
      run: |
        python3 -m venv .venv                 # Create virtual environment
        
        # Activate virtual environment based on OS
        if [ "$(uname)" == "Darwin" ] || [ "$(uname)" == "Linux" ]; then
          source .venv/bin/activate           # macOS/Linux
        else
          .\.venv\Scripts\activate            # Windows
        fi
    
        pip install --upgrade pip            # Upgrade pip
        pip install -r requirements.txt      # Install dependencies from requirements.txt

    - name: Build site
      run: |
        # Activate virtual environment based on OS
        if [ "$(uname)" == "Darwin" ] || [ "$(uname)" == "Linux" ]; then     
          source .venv/bin/activate           # macOS/Linux
        else
         .\.venv\Scripts\activate            # Windows
        fi
    
        mkdocs build -f docs/mkdocs.yml -d site   # Build the MkDocs site

    # -----------------  Deployment  -----------------
    - name: Deploy via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEPLOY_HOST:     ${{ vars.DEPLOY_HOST }}    
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

        # choose the correct host variable
        HOST=${SSH_HOST:-$DEPLOY_HOST}

        scp -o StrictHostKeyChecking=no -r ./docs/site/* \
            support@$HOST:"$DEPLOY_PATH/"
